name: Terraform Workflow

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Apply or Destroy"
        required: true
        default: "apply" 

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0 

      - name: Terraform Init
        run: terraform init

      - name: Apply or Destroy
        run: terraform ${{ github.event.inputs.action }} -auto-approve
