name: Terraform Workflow

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Apply or Destroy"
        required: true
        default: "apply" # You can change the default action

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0 # Change to your desired Terraform version

      - name: Terraform Init
        run: terraform init

      - name: Apply or Destroy
        run: |
          if [ ${{ github.event.inputs.action }} == 'apply' ]; then
            terraform apply -auto-approve
          elif [ ${{ github.event.inputs.action }} == 'destroy' ]; then
            terraform destroy -auto-approve
          else
            echo "Invalid action specified."
            exit 1
          fi
